image: golang:latest

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - _GO/

after_script:
  - cp -R $GOPATH ./_GO

before_script:
  - mkdir -p _GO/
  - cp -R _GO $GOPATH

stages:
  - test
  - lint

test:
  stage: test
  script:
    - go get ./...
    - go fmt -x ./...
    - go test -v -race ./...

golangcli:
  stage: lint
  image: golangci/golangci-lint:v1.17.1
  script:
    - go get ./...
    - golangci-lint run --enable-all --disable=lll,gochecknoglobals,gochecknoinits ./...
