image: golang:latest

variables:
  GOFLAGS: "-mod=vendor"

stages:
  - check

test:
  stage: check
  script:
    - go test -v -race ./...

golangcli:
  stage: check
  image: golangci/golangci-lint:v1.17.1
  script:
    - golangci-lint run -v -D govet
