image: golang:latest

variables:
  GOFLAGS: "-mod=vendor"

stages:
  - test
  - lint

test:
  stage: test
  script:
    - go test -v -race ./...

golangcli:
  stage: lint
  image: golangci/golangci-lint:v1.17.1
  script:
    - go fmt -x ./...
    - golangci-lint run -v
