apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusNodeSet
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-ns
spec:
  disableDRBDKernelModuleInjection: {{ .Values.operator.nodeSet.spec.disableDRBDKernelModuleInjection }}
  storagePools:
    lvmPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmPoolVgName }}
    lvmThinPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmThinPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmThinPoolVgName }}
      thinVolume: {{ .Values.operator.nodeSet.spec.lvmThinPoolLvName }}
  drbdRepoCred: {{ .Values.repoCreds }}
