apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusNodeSet
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-ns
spec:
  disableDRBDKernelModuleInjection: {{ .Values.operator.nodeSet.spec.disableDRBDKernelModuleInjection }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  satelliteImage: {{ .Values.operator.nodeSet.spec.satelliteImage }}
  satelliteVersion: {{ .Values.operator.nodeSet.spec.satelliteVersion }}
  kernelModImage: {{ .Values.operator.nodeSet.spec.kernelModImage }}
  kernelModVersion: {{ .Values.operator.nodeSet.spec.kernelModVersion }}
  storagePools:
    lvmPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmPoolVgName }}
    lvmThinPools:
    - name: {{ .Values.operator.nodeSet.spec.lvmThinPoolName }}
      volumeGroup: {{ .Values.operator.nodeSet.spec.lvmThinPoolVgName }}
      thinVolume: {{ .Values.operator.nodeSet.spec.lvmThinPoolLvName }}
