apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusControllerSet
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-cs
spec:
  etcdURL: etcd://{{ .Release.Name }}-etcd:2379  # TODO: Fix
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  controllerImage: {{ .Values.operator.controllerSet.spec.controllerImage }}
  controllerVersion: {{ .Values.operator.controllerSet.spec.controllerVersion }}