apiVersion: v2
name: piraeus
description: A Helm chart for Piraeus Operator
type: application
version: 0.2.1     # Chart Version
appVersion: 0.2.0  # Application Version

dependencies:
  - name: "etcd"
    version: "4.4.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: etcd.enabled
