etcd:
  persistence:
    enabled: false
  auth:
    rbac:
      enabled: false
  statefulset:
    replicaCount: 3
  envVarsConfigMap: "etcd-env-vars"
csi:
  image:
    repo: "quay.io/piraeusdatastore"
    name: "linstor-csi"
    version: "v0.7.3"
repoCreds: drbdiocred     # <- Specify the kubernetes secret name here
operator:
  image:
    repo: "quay.io/piraeusdatastore"
    name: "piraeus-operator"
    version: "v0.1.0"
  nodeSet:
    spec:
      disableDRBDKernelModuleInjection: false
      satelliteImage: "quay.io/piraeusdatastore/piraeus-server"
      satelliteVersion: "v1.4.2"
      lvmPoolName: "lvm-thick"
      lvmPoolVgName: "drbdpool"      # <- Volume Group name of the thick storage pool
      lvmThinPoolName: "lvm-thin"
      lvmThinPoolVgName: "drbdpool"  # <- Volume Group name of the thin storage pool
      lvmThinPoolLvName: "thinpool"  # <- Logical Volume name of the thin pool
    
