etcd:
  persistence:
    enabled: true
    size: 1Gi
  volumePermissions:
    enabled: true
  auth:
    rbac:
      enabled: false
  statefulset:
    replicaCount: 3
  envVarsConfigMap: "etcd-env-vars"
csi:
  image:
    repo: "quay.io/piraeusdatastore"
    name: "piraeus-csi"
    version: "v0.7.4"
drbdRepoCred: drbdiocred     # <- Specify the kubernetes secret name here
operator:
  image:
    repo: "quay.io/piraeusdatastore"
    name: "piraeus-operator"
    version: "v0.1.4"
  controllerSet:
    spec:
      controllerImage: "quay.io/piraeusdatastore/piraeus-server"
      controllerVersion: "v1.4.3"
  nodeSet:
    spec:
      drbdKernelModuleInjectionMode: Compile
      satelliteImage: "quay.io/piraeusdatastore/piraeus-server"
      satelliteVersion: "v1.4.3"
      kernelModImage: "quay.io/piraeusdatastore/drbd9-bionic"
      kernelModVersion: "v9.0.21"
      lvmPoolName: "lvm-thick"
      lvmPoolVgName: "drbdpool"      # <- Volume Group name of the thick storage pool
      lvmThinPoolName: "lvm-thin"
      lvmThinPoolVgName: "drbdpool"  # <- Volume Group name of the thin storage pool
      lvmThinPoolLvName: "thinpool"  # <- Logical Volume name of the thin pool
